#!/bin/bash

# Create the database container
docker build -t gatewayd_db ./postgresql

# Start the database server
docker run -d --name db gatewayd_db

# Create the database user
docker run -it --link db:db gatewayd_db psql -h db -U postgres -c "create user gatewayd_user with password 'password'"

# Create the database to use
docker run -it --link db:db gatewayd_db psql -h db -U postgres -c "create database gateway_db with owner gatewayd_user"

# Create the gatewayd container
docker build -t gatewayd ./gatewayd

# Run the migration script
docker run -it --link db:db gatewayd /bin/bash -c "cd /gatewayd && grunt migrate"

