#!/bin/bash

# Create the database container
docker pull adamcmiel/postgres:1.0.0

# Start the database server
docker run -d --name db adamcmiel/postgres:1.0.0

# Create the database user
docker run -it --link db:db adamcmiel/postgres:1.0.0 psql -h db -U postgres -c "create user gatewayd_user with password 'password'"

# Create the database to use
docker run -it --link db:db adamcmiel/postgres:1.0.0 psql -h db -U postgres -c "create database gateway_db with owner gatewayd_user"

# Create the gatewayd container
docker pull adamcmiel/gatewayd:1.1.0

# Run the migration script
docker run -it --link db:db adamcmiel/gatewayd:1.1.0 /bin/bash -c "cd /gatewayd && grunt migrate"
